apiVersion: apps/v1
kind: Deployment
metadata:
  name: $IMSQL_TERMINAL_SERVER
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $IMSQL_TERMINAL_SERVER
  template:
    metadata:
      labels:
        app: $IMSQL_TERMINAL_SERVER
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: $IMSQL_TERMINAL_SERVER
        image: $ACR/raincodeimsqlterminalserver:latest
        volumeMounts:
          - name: $IMSQL_TS_VOLUME
            mountPath: /app
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 5000
        env:
        - name: REGION_ID
          valueFrom:
            secretKeyRef:
              name: $IMSQL_CONFIG_SECRET
              key: regionid
        - name: CONN_STRING
          valueFrom:
            secretKeyRef:
              name: $IMSQL_CONFIG_SECRET
              key: configdbconnstring
        - name: PORT_NO
          value: "5000"
      volumes:
      - name: $IMSQL_TS_VOLUME
        persistentVolumeClaim:
          claimName: $IMSQL_TS_VOLUME_CLAIM
---
apiVersion: v1
kind: Service
metadata:
  name: $IMSQL_TERMINAL_SERVER
  namespace: $NAMESPACE
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 992
    targetPort: 5000
  selector:
    app: $IMSQL_TERMINAL_SERVER