apiVersion: v1
kind: PersistentVolume
metadata:
  name: $IMSQL_PS_VOLUME
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: $IMSQL_STORAGE_SECRET
    shareName: $IMSQL_FILE_SHARE/ProcessingServer
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $IMSQL_TS_VOLUME
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: $IMSQL_STORAGE_SECRET
    shareName: $IMSQL_FILE_SHARE/TerminalServer
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl