apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $IMSQL_PS_VOLUME_CLAIM
  namespace: $NAMESPACE
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: $IMSQL_PS_VOLUME
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $IMSQL_TS_VOLUME_CLAIM
  namespace: $NAMESPACE
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: $IMSQL_TS_VOLUME
  resources:
    requests:
      storage: 5Gi