apiVersion: v1
kind: PersistentVolume
metadata:
  name: $VOLUME_CLAIM_NAME
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: $SECRET_NAME 
    shareName: $AZURE_FILE_SHARE
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl