apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $VOLUME_CLAIM_NAME
  namespace: $NAMESPACE
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi